# Generated by Django 2.2.15 on 2020-08-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20200827_1439"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetail",
            name="price_id",
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="paymentdetail",
            name="product_id",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
