# Generated by Django 2.2.15 on 2020-08-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_paymentdetail_subscription_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentdetail",
            name="price",
        ),
        migrations.RemoveField(
            model_name="paymentdetail",
            name="price_id",
        ),
        migrations.RemoveField(
            model_name="paymentdetail",
            name="subscription_id",
        ),
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=0.0)),
                ("price_id", models.CharField(max_length=250, null=True)),
                ("subscription_id", models.CharField(max_length=250, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="users.PaymentDetail",
                    ),
                ),
            ],
        ),
    ]
