# Generated by Django 2.2.16 on 2020-09-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_auto_20200907_1350"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="success",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
