# Generated by Django 2.2.16 on 2020-10-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_auto_20200924_1605"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
