# Generated by Django 2.2.16 on 2020-12-17 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_auto_20201217_0811"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkoutTypes",
            new_name="WorkoutType",
        ),
        migrations.AlterField(
            model_name="profilepictures",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
