# Generated by Django 2.2.18 on 2021-02-08 11:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_auto_20210127_1228"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="geotag",
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
