# Generated by Django 2.2.18 on 2021-02-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_user_geotag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilepictures",
            name="picture",
            field=models.ImageField(max_length=200, upload_to="user_photo"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, max_length=200, null=True, upload_to="user_photo"
            ),
        ),
    ]
