# Generated by Django 2.2.19 on 2021-03-26 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0010_auto_20210316_1234"),
        ("users", "0021_user_referral_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentdetail",
            name="client_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainer_classes.ClientClassSignUp",
            ),
        ),
        migrations.AlterField(
            model_name="paymentdetail",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_transferred",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="price_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="subscription_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
