# Generated by Django 2.2.20 on 2021-04-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_user_stripe_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(default="I like sport", null=True),
        ),
    ]
