# Generated by Django 2.2.20 on 2021-04-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_auto_20210408_1058"),
        ("users", "0025_merge_20210408_0906"),
    ]

    operations = []
