# Generated by Django 2.2.20 on 2021-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0026_merge_20210408_1147"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(default="Undercard trainer", null=True),
        ),
    ]
