# Generated by Django 2.2.20 on 2021-05-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_auto_20210504_0827"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["-updated_date_time"], name="users_price_updated_225593_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["user_type"], name="users_user_user_ty_4573bb_idx"
            ),
        ),
    ]
