# Generated by Django 2.2.20 on 2021-05-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0029_auto_20210506_0829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentdetail",
            name="client_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_client_class",
                to="trainer_classes.ClientClassSignUp",
            ),
        ),
    ]
