# Generated by Django 2.2.20 on 2021-05-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0030_auto_20210507_0843"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paymentdetail",
            index=models.Index(
                fields=["client", "trainer"], name="users_payme_client__285083_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentdetail",
            index=models.Index(
                fields=["trainer", "client_class"], name="users_payme_trainer_3daf9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(
                fields=["recurring"], name="users_price_recurri_5ea33a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="price",
            index=models.Index(fields=["payment"], name="users_price_payment_21142f_idx"),
        ),
        migrations.AddIndex(
            model_name="profilepictures",
            index=models.Index(fields=["user"], name="users_profi_user_id_dfb7f6_idx"),
        ),
    ]
