# Generated by Django 2.2.23 on 2021-06-01 13:33

from django.db import migrations, models


def update_default_bio(apps, *args, **kwargs):
    User = apps.get_model("users", "User")
    for user in User.objects.all():
        if user.bio and "Undercard" in user.bio:
            User.objects.filter(pk=user.pk).update(
                bio=user.bio.replace("Undercard", "Rec")
            )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0037_create_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(default="Rec trainer", null=True),
        ),
        migrations.RunPython(update_default_bio, reverse_code=migrations.RunPython.noop),
    ]
