# Generated by Django 2.2.24 on 2021-07-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20210708_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('trainer', 'Trainer'), ('client', 'Client')], default='client', max_length=10),
        ),
    ]
