export const CREATE_PROFILE_REQUEST = 'Profile/CREATE/REQUEST';
export const CREATE_PROFILE_SUCCESS = 'Profile/CREATE/SUCCESS';
export const CREATE_PROFILE_ERROR = 'Profile/CREATE/ERROR';

export const UPDATE_STRIPE_ID_PROFILE_REQUEST =
  'Profile/UPDATE_STRIPE_ID_PROFILE_REQUEST';
export const UPDATE_STRIPE_ID_PROFILE_SUCCESS =
  'Profile/UPDATE_STRIPE_ID_PROFILE_SUCCESS';
export const UPDATE_STRIPE_ID_PROFILE_ERROR =
  'Profile/UPDATE_STRIPE_ID_PROFILE_ERROR';

export const PROFILE_IMAGE_UPLOAD_SUCCESS =
  'Profile/PROFILE_IMAGE_UPLOAD_SUCCESS/SUCCESS';
export const PROFILE_IMAGES_UPLOAD_SUCCESS =
  'Profile/PROFILE_IMAGES_UPLOAD_SUCCESS/SUCCESS';

export const SEARCH_PROFILE_REQUEST = 'Profile/SEARCH/REQUEST';
export const GET_PROFILE_REQUEST = 'Profile/GET/REQUEST';
export const GET_PROFILE_SUCCESS = 'Profile/GET/SUCCESS';
export const SEARCH_PROFILE_SUCCESS = 'Profile/SEARCH/SUCCESS';
export const SEARCH_PROFILE_ERROR = 'Profile/SEARCH/ERROR';

export const MESSAGE_CHAT_OPEN = 'Profile/MESSAGE_CHAT_OPEN';
export const MESSAGE_CHAT_SET_USER = 'Profile/MESSAGE_CHAT_SET_USER';

export const UPDATEPROFILEIMAGE_REQUEST = 'Profile/UpdateProfilePicture';
export const UPDATEPROFILEIMAGE_REQUEST_SUCCESS =
  'Profile/UPDATEPROFILEIMAGE_REQUEST_SUCCESS';
export const UPDATEPROFILEIMAGES_REQUEST_SUCCESS =
  'Profile/UPDATEPROFILEIMAGES_REQUEST_SUCCESS';

export const CALENDAR_ADD_EVENT_CLEAR =
  'CALENDAR/CALENDAR_ADD_EVENT_CLEAR/CLEAR';

export const PROFILE_PAYMENT_COUNTRY_UPDATE = 'PROFILE/PAYMENT/COUNTRY';

//Payments Account
export const CREATE_STRIPE_ACCOUNT_REQUEST = 'Profile/CREATE_STRIPE_ACCOUNT';
export const CREATE_STRIPE_ACCOUNT_REQUEST_SUCCESS =
  'Profile/CREATE_STRIPE_ACCOUNT_REQUEST_SUCCESS';

export const LOGIN_STRIPE_ACCOUNT_REQUEST =
  'Profile/LOGIN_STRIPE_ACCOUNT_REQUEST';
export const LOGIN_STRIPE_ACCOUNT_REQUEST_SUCCESS =
  'Profile/LOGIN_STRIPE_ACCOUNT_REQUEST_SUCCESS';

export const GET_STRIPE_ACCOUNT_REQUEST = 'Profile/GET_STRIPE_ACCOUNT_REQUEST';
export const GET_STRIPE_ACCOUNT_REQUEST_SUCCESS =
  'Profile/GET_STRIPE_ACCOUNT_REQUEST_SUCCESS';

export const GET_STRIPE_CARDS_REQUEST = 'Profile/GET_STRIPE_CARDS_REQUEST';
export const GET_STRIPE_CARDS_REQUEST_SUCCESS =
  'Profile/GET_STRIPE_CARDS_REQUEST_SUCCESS';

export const POST_STRIPE_CARD_SUCCESS = 'Profile/POST_STRIPE_CARD_SUCCESS';

export const DELETE_STRIPE_CARDS_REQUEST =
  'Profile/DELETE_STRIPE_CARDS_REQUEST';
export const DELETE_STRIPE_CARDS_REQUEST_SUCCESS =
  'Profile/DELETE_STRIPE_CARDS_REQUEST_SUCCESS';

export const POST_STRIPE_CARDS_REQUEST = 'Profile/POST_STRIPE_CARDS_REQUEST';
export const POST_STRIPE_CARDS_REQUEST_SUCCESS =
  'Profile/POST_STRIPE_CARDS_REQUEST_SUCCESS';

export const CREATE_SUBSCRIPTIONS_REQUEST =
  'Profile/CREATE_SUBSCRIPTIONS_REQUEST';
export const CREATE_SUBSCRIPTIONS_REQUEST_SUCCESS =
  'Profile/CREATE_SUBSCRIPTIONS_REQUEST_SUCCESS';

export const GET_SUBSCRIPTION_REQUEST = 'Profile/GET_SUBSCRIPTION_REQUEST';
export const GET_SUBSCRIPTION_REQUEST_SUCCESS =
  'Profile/GET_SUBSCRIPTION_REQUEST_SUCCESS';

export const CANCEL_SUBSCRIPTION_REQUEST =
  'Profile/CANCEL_SUBSCRIPTION_REQUEST';
export const CANCEL_SUBSCRIPTION_REQUEST_SUCCESS =
  'Profile/CANCEL_SUBSCRIPTION_REQUEST_SUCCESS';

export const CHANGE_PHOTOS = 'Profile/CHANGE_PHOTOS';
export const CHANGE_FIRST_NAME = 'Profile/CHANGE_FIRST_NAME';
export const CHANGE_LAST_NAME = 'Profile/CHANGE_LAST_NAME';
export const CHANGE_INSTAGRAM_LINK = 'Profile/CHANGE_INSTAGRAM_LINK';
export const WORKOUT_TYPES_ADD = 'Profile/WORKOUT_TYPES_ADD';
export const WORKOUT_TYPES_REMOVE = 'Profile/WORKOUT_TYPES_REMOVE';
export const CHANGE_ABOUT = 'Profile/CHANGE_ABOUT';
export const SAVE_TRAINER_PROFILE = 'Profile/SAVE_TRAINER_PROFILE';

export const SET_WORKOUT_TYPES = 'Profile/SET_WORKOUT_TYPES';
export const SET_USER_TYPE = 'Profile/SET_USER_TYPE';
export const PUT_REFERRAL_USER = 'Profile/PUT_REFERRAL_USER';

export const LOAD_MORE_PROFILES = 'Profile/LOAD_MORE_PROFILES';
export const LOAD_MORE_PROFILES_LOADING = 'Profile/LOAD_MORE_PROFILES';
export const GET_PAYMENTS_FOR_MONTH = 'Profile/GET_PAYMENTS_FOR_MONTH';
export const GET_PAYMENTS_FOR_MONTH_SUCCESS =
  'Profile/GET_PAYMENTS_FOR_MONTH_SUCCESS';
export const GET_PAYMENTS_FOR_MONTH_FAILURE =
  'Profile/GET_PAYMENTS_FOR_MONTH_FAILURE';
export const RESET_PAYMENTS_FOR_MONTH = 'Profile/RESET_PAYMENTS_FOR_MONTH';

export const GET_PAYMENTS_FOR_USER = 'Profile/GET_PAYMENTS_FOR_USER';
export const GET_PAYMENTS_FOR_USER_SUCCESS =
  'Profile/GET_PAYMENTS_FOR_USER_SUCCESS';
export const GET_PAYMENTS_FOR_USER_FAILURE =
  'Profile/GET_PAYMENTS_FOR_USER_FAILURE';
export const RESET_PAYMENTS_FOR_USER = 'Profile/RESET_PAYMENTS_FOR_USER';

export const SET_PAYMENTS_LOADING = 'Profile/SET_PAYMENTS_LOADING';
export const CALL_UNSUBSCRIBE_PAYMENT_REQUEST =
  'Profile/CALL_UNSUBSCRIBE_PAYMENT_REQUEST';
