version: "3"

services:

  web:
    build:
      context: .
    links:
      - postgres
      - redis
    env_file: ../.env
    volumes:
      - ./:/opt/webapp
    ports:
      - "8000:8000"

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    expose:
      - "5432"
    command:
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "shared_buffers=32MB"
    environment:
        POSTGRES_DB: 'rec'
        POSTGRES_USER: 'rec'
        POSTGRES_PASSWORD: 'rec'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      
  redis:
    image: redis
    ports:
      - "6379:6379"

volumes:
  postgresql:
  redis:
  migrations:

networks: 
  default: 
      name: local-rec 
  
