# Generated by Django 2.2.24 on 2021-09-09 20:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import push_notifications.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainer_classes', '0038_auto_20210909_1948'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('push_notifications', '0007_uniquesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockAPNSDevice',
            fields=[
                ('apnsdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.APNSDevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.apnsdevice',),
        ),
        migrations.CreateModel(
            name='MockMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_class', models.CharField(max_length=1024)),
                ('device_id', models.UUIDField(verbose_name=push_notifications.models.Device)),
                ('when', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
            ],
        ),
        migrations.CreateModel(
            name='MockWebPushDevice',
            fields=[
                ('webpushdevice_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='push_notifications.WebPushDevice')),
            ],
            options={
                'abstract': False,
            },
            bases=('push_notifications.webpushdevice',),
        ),
        migrations.CreateModel(
            name='PreClassTrainerPushLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_undercard_push.preclasstrainerpushlog_set+', to='contenttypes.ContentType')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trainer_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer_classes.TrainerClass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
