# Generated by Django 2.2.24 on 2021-09-13 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import undercard_push.models.base


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('trainer_classes', '0038_auto_20210909_1948'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('undercard_push', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preclasstrainerpushlog',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[undercard_push.models.base.is_trainer]),
        ),
        migrations.CreateModel(
            name='PreClassClientPushLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, validators=[undercard_push.models.base.is_client])),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_undercard_push.preclassclientpushlog_set+', to='contenttypes.ContentType')),
                ('trainer_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer_classes.TrainerClass')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
