# Generated by Django 2.2.24 on 2021-09-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('undercard_push', '0006_auto_20210913_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preclassclientpushlog',
            name='trainer_class',
        ),
    ]
