disabled_rules:
  - line_length
  - identifier_name
  - multiple_closures_with_trailing_closure
  - todo

opt_in_rules:
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - file_name
  - unneeded_parentheses_in_closure_argument
  - empty_count

file_length:
  warning: 210
  error: 250

included:
  - Shared
  - iOS
  - macOS
  - Unit Tests
