# Generated by Django 2.2.18 on 2021-02-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0002_auto_20210205_1258"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientclasssignup",
            name="stripe_customer_id",
        ),
        migrations.AddField(
            model_name="clientclasssignup",
            name="payment_method",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="clientclasssignup",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_paid", "Not Yet Paid"),
                    ("moderate", "Paid"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                ],
                default="not_paid",
                max_length=10,
            ),
        ),
    ]
