# Generated by Django 2.2.18 on 2021-02-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0004_auto_20210212_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientclasssignup",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
