# Generated by Django 2.2.20 on 2021-05-06 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0013_auto_20210504_0840"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="all_client",
        ),
    ]
