# Generated by Django 2.2.20 on 2021-05-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0014_remove_notification_all_client"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clientclasssignup",
            index=models.Index(
                fields=["trainer_class"], name="client_clas_trainer_761a1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientclasssignup",
            index=models.Index(
                fields=["-created_at"], name="client_clas_created_412135_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainerclass",
            index=models.Index(fields=["hash"], name="trainer_cla_hash_2b36ee_idx"),
        ),
        migrations.AddIndex(
            model_name="trainerclass",
            index=models.Index(
                fields=["start_time"], name="trainer_cla_start_t_af9fa4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainerclass",
            index=models.Index(
                fields=["published_at"], name="trainer_cla_publish_c7ff8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainerclass",
            index=models.Index(
                fields=["promo_code"], name="trainer_cla_promo_c_ae35db_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainerclass",
            index=models.Index(fields=["type"], name="trainer_cla_type_c5974f_idx"),
        ),
        migrations.AddIndex(
            model_name="trainerclass",
            index=models.Index(fields=["free"], name="trainer_cla_free_fa98c9_idx"),
        ),
        migrations.AddIndex(
            model_name="trainerclass",
            index=models.Index(fields=["author"], name="trainer_cla_author__6a425e_idx"),
        ),
    ]
