# Generated by Django 2.2.24 on 2021-06-03 10:43

import autoslug.fields
from django.db import migrations


def set_slug_trainer_class(apps, *args, **kwargs):
    TrainerClass = apps.get_model("trainer_classes", "TrainerClass")
    for trainer_class in TrainerClass.objects.all():
        trainer_class.save()


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0017_auto_20210521_0821"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerclass",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.RunPython(
            set_slug_trainer_class, reverse_code=migrations.RunPython.noop
        ),
    ]
