# Generated by Django 2.2.24 on 2021-06-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0020_auto_20210608_1300"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_subject",
            field=models.CharField(
                blank=True, default="Getrec", max_length=255, null=True
            ),
        ),
    ]
