# Generated by Django 2.2.24 on 2021-06-15 10:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0022_add_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerclass",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                blank=True, editable=False, null=True, populate_from="name", unique=True
            ),
        )
    ]
