# Generated by Django 2.2.24 on 2021-07-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('trainer_classes', '0029_auto_20210708_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientclasssignup',
            name='capture_payment_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='django_celery_beat.PeriodicTask'),
        ),
        migrations.AlterField(
            model_name='clientclasssignup',
            name='reminder_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.PeriodicTask'),
        ),
    ]
