# Generated by Django 2.2.24 on 2021-09-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0034_auto_20210808_1921"),
    ]

    operations = [
       
    ]
