# Generated by Django 2.2.24 on 2021-09-24 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('trainer_classes', '0040_auto_20210923_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerclass',
            name='payout_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='django_celery_beat.PeriodicTask'),
        ),
        migrations.RemoveField(
            model_name='clientclasssignup',
            name='payout_task',
        ),
    ]
