export const SET_NAME_OF_CLASS = 'Classes/SET_NAME_OF_CLASS';
export const SET_START_DATE = 'Classes/SET_START_DATE';
export const SET_DURATION = 'Classes/SET_DURATION';
export const SET_REPEAT = 'Classes/SET_REPEAT';
export const ADD_TAG = 'Classes/ADD_TAG';
export const REMOVE_TAG = 'Classes/REMOVE_TAG';
export const CHANGE_PHOTO = 'Classes/CHANGE_PHOTO';
export const DELETE_PHOTO = 'Classes/DELETE_PHOTO';
export const SET_DETAILS_OF_CLASS = 'Classes/SET_DETAILS_OF_CLASS';
export const SET_EQUIPMENTS_OF_CLASS = 'Classes/SET_EQUIPMENTS_OF_CLASS';
export const SET_LOCATION = 'Classes/SET_LOCATION';
export const SET_LOCATION_NOTES = 'Classes/SET_LOCATION_NOTES';
export const SET_SAFE_PROTOCOL = 'Classes/SET_SAFE_PROTOCOL';
export const SET_VIRTUAL_LINK = 'Classes/SET_ZOOM_LINK';
export const SET_TYPE_OF_CLASSES = 'Classes/SET_TYPE_OF_CLASSES';
export const SET_VIRTUAL_PASSWORD = 'Classes/SET_ZOOM_PAZZWORD';
export const SET_ATTENDEE_PRICE = 'Classes/SET_ATTENDEE_PRICE';
export const SET_ATTENDEE_LIMIT = 'Classes/SET_ATTENDEE_NUMBER';
export const SET_ATTENDEE_UNLIMITED = 'Classes/SET_ATTENDEE_UNLIMITED';
export const SET_PROMO_VALUE = 'Classes/SET_PROMO_VALUE';
export const SET_PROMO_CONFIRM = 'Classes/SET_PROMO_CONFIRM';
export const SET_POLICY = 'Classes/SET_POLICY';
export const SET_CLASS_IN_DRAFT = 'Classes/SET_CLASS_IN_DRAFT';
export const CLEAR_CURRENT_CLASS = 'Classes/CLEAR_CURRENT_CLASS';
export const SET_IN_DRAFTS = 'Classes/SET_IN_DRAFTS';
export const SET_CLASS_FOR_PREVIEW = 'Classes/SET_CLASS_FOR_PREVIEW';
export const SET_DRAFT_FOR_EDIT = 'Classes/SET_DRAFT_FOR_EDIT';
export const SET_CLASS_FOR_DUPLICATE = 'Classes/SET_CLASS_FOR_DUPLICATE';
export const SAVE_EXISTING_DRAFT = 'Classes/SAVE_EXISTING_DRAFT';
export const SET_END_OF_REPEAT = 'Classes/SET_END_OF_REPEAT';
export const SET_UPCOMING_CLASSES = 'Classes/SET_UPCOMING_CLASSES';

export const CLASS_FETCHING = 'Classes/CLASS_FETCHING';
export const GET_TRAINER_CLASSES_FETCHING =
  'Classes/GET_TRAINER_CLASSES_FETCHING';
export const GET_TRAINER_CLASS_SUCCESS = 'Classes/GET_TRAINER_CLASS_SUCCESS';
export const PUBLISH_NEW_CLASS_SUCCESS = 'Classes/PUBLISH_CLASSES_SUCCESS';
export const FINISH_PUBLISHING = 'Classes/FINISH_PUBLISHING';
export const GET_TRAINER_CLASS_ERROR = 'Classes/GET_TRAINER_CLASS_ERROR';
export const PUBLISH_NEW_CLASS_REQUEST = 'Classes/PUBLISH_NEW_CLASS_REQUEST';
export const GET_TRAINER_CLASSES_REQUEST =
  'Classes/GET_TRAINER_CLASSES_REQUEST';
export const EDIT_TRAINER_CLASSES_REQUEST = 'EDIT_TRAINER_CLASSES_REQUEST';
export const SAVE_EXISTING_CLASS_SUCCESS =
  'Classes/SAVE_EXISTING_CLASS_SUCCESS';
export const SAVE_DRAFT_REQUEST = 'Classes/SAVE_DRAFT_REQUEST';
export const SAVE_EXISTING_DRAFT_REQUEST =
  'Classes/SAVE_EXISTING_DRAFT_REQUEST';
export const SET_PAST_CLASS_FOR_PREVIEW = 'Classes/SET_PAST_CLASS_FOR_PREVIEW';
export const SET_IMAGE_FOR_CLASS = 'Classes/SET_IMAGE_FOR_CLASS';
export const GET_SIGNUP_CLIENTS = 'Classes/GET_SIGNUP_CLIENTS';
export const CLIENTS_SIGNUP_CLEAR = 'Classes/CLIENTS_SIGNUP_CLEAR';
export const GET_SIGNUP_CLIENTS_SUCCESS = 'Classes/GET_SIGNUP_CLIENTS_SUCCESS';
export const SET_CLASS_FREE = 'Classes/SET_CLASS_FREE';

export const CANCEL_CLASS_REQUEST = 'Classes/CANCEL_CLASS_REQUEST';

export const CANCEL_CLASS_REQUEST_LOADING =
  'Classes/CANCEL_CLASS_REQUEST_LOADING';
