export const CALENDAR_GOOGLE_LOGIN_REQUEST = 'CALENDAR/GOOGLE_LOGIN/REQUEST';
export const CALENDAR_SET_USER = 'CALENDAR/SET_USER';
export const CALENDAR_GOOGLE_LOGIN_ERROR = 'CALENDAR/GOOGLE_LOGIN/ERROR';

export const SET_GOOGLE_TOKEN = 'CALENDAR/SET_GOOGLE_TOKEN/REQUEST';

export const CHAT_TOKEN_DATA_REQUEST =
  'CALENDAR/CHAT_TOKEN_DATA_REQUEST/REQUEST';
export const CHAT_TOKEN_DATA_SUCCESS =
  'CALENDAR/CHAT_TOKEN_DATA_SUCCESS/SUCCESS';
export const CHAT_TOKEN_DATA_ERROR = 'CALENDAR/CHAT_TOKEN_DATA_ERROR/ERROR';

export const CREATE_PROFILE_SUCCESS = 'Profile/CREATE/SUCCESS';
export const SEARCH_PROFILE_SUCCESS = 'Profile/SEARCH/SUCCESS';
export const GET_PROFILE_SUCCESS = 'Profile/GET/SUCCESS';
export const PROFILE_IMAGE_UPLOAD_SUCCESS =
  'Profile/PROFILE_IMAGE_UPLOAD_SUCCESS/SUCCESS';

export const CALENDAR_GOOGLE_LOGOUT_REQUEST = 'CALENDAR/GOOGLE_LOGOUT/REQUEST';
export const CALENDAR_GOOGLE_LOGOUT_SUCCESS = 'CALENDAR/GOOGLE_LOGOUT/SUCCESS';
export const CALENDAR_GOOGLE_LOGOUT_ERROR = 'CALENDAR/GOOGLE_LOGOUT/ERROR';

export const CALENDAR_ADD_EVENT_REQUEST =
  'CALENDAR/CALENDAR_ADD_EVENT_REQUEST/REQUEST';
export const CALENDAR_ADD_EVENT_SUCCESS =
  'CALENDAR/CALENDAR_ADD_EVENT_SUCCESS/SUCCESS';
export const CALENDAR_ADD_EVENT_ERROR =
  'CALENDAR/CALENDAR_ADD_EVENT_ERROR/ERROR';

export const CALENDAR_ADD_EVENT_CLEAR =
  'CALENDAR/CALENDAR_ADD_EVENT_CLEAR/CLEAR';

export const CALENDAR_APPLE_LOGIN_REQUEST = 'CALENDAR/APPLE_LOGIN/REQUEST';
export const CALENDAR_APPLE_LOGIN_SUCCESS = 'CALENDAR/APPLE_LOGIN/SUCCESS';
export const CALENDAR_APPLE_LOGIN_ERROR = 'CALENDAR/APPLE_LOGIN/ERROR';
