# Generated by Django 2.2.15 on 2020-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0002_auto_20200804_0612"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphoto",
            name="photo",
            field=models.URLField(),
        ),
    ]
