# Generated by Django 2.2.24 on 2021-10-27 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0005_delete_dislike'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
