# Generated by Django 2.2.15 on 2020-08-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="lat",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="long",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
