# Generated by Django 2.2.16 on 2020-11-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_auto_20200816_0609"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="slug",
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
