# Generated by Django 2.2.24 on 2021-10-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_update_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='inbox',
        ),
    ]
