# Generated by Django 2.2.14 on 2020-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dating", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userphoto",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="user_photo"),
        ),
    ]
