# Generated by Django 2.2.24 on 2021-10-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0004_auto_20200816_0604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dislike',
        ),
    ]
