# Generated by Django 2.2.24 on 2021-10-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0007_auto_20211028_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPhoto',
        ),
    ]
