# Generated by Django 2.2.24 on 2021-09-13 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0038_auto_20210909_1948'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('undercard_push', '0004_auto_20210913_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientClassSignupPushLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_class_signup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainer_classes.ClientClassSignUp')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_undercard_push.clientclasssignuppushlog_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
    ]
