# Generated by Django 2.2.15 on 2020-08-06 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="description",
        ),
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
    ]
