# Generated by Django 2.2.14 on 2020-08-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200714_1915"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="user_photo"),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("trainer", "Trainer"), ("client", "Client")],
                default="client",
                max_length=10,
            ),
        ),
    ]
