# Generated by Django 2.2.15 on 2020-09-07 13:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_price_recurring"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="create_date_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="price",
            name="updated_date_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
