# Generated by Django 2.2.19 on 2021-03-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="referral_code",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
