# Generated by Django 2.2.19 on 2021-04-01 13:00
import re

from django.db import migrations, models


def migrate_stripe_accounts(apps, *args, **kwargs):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        if user.stripe_customer_id and re.match(r"^acct", user.stripe_customer_id):
            user.stripe_account_id = user.stripe_customer_id
            user.stripe_customer_id = None
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_auto_20210326_0933"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stripe_account_id",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.RunPython(migrate_stripe_accounts),
    ]
