# Generated by Django 2.2.20 on 2021-04-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_user_stripe_account_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="invoice_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
