# Generated by Django 2.2.20 on 2021-04-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_auto_20210408_0900"),
        ("users", "0024_price_invoice_id"),
    ]

    operations = []
