# Generated by Django 2.2.20 on 2021-04-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_auto_20210408_0900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("trainer", "Trainer"), ("client", "Client")],
                default="trainer",
                max_length=10,
            ),
        ),
    ]
