# Generated by Django 2.2.20 on 2021-05-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_auto_20210416_1232"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={"ordering": ["-updated_date_time"]},
        ),
    ]
