# Generated by Django 2.2.20 on 2021-05-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0031_auto_20210507_1220"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="price",
            options={},
        ),
    ]
