# Generated by Django 2.2.20 on 2021-05-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="charge_id",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
