# Generated by Django 2.2.23 on 2021-05-25 15:53

import os

from django.db import migrations, models

import users.models


def set_users_hash(apps, *args, **kwargs):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        user.hash = "".join("%02x" % x for x in os.urandom(8))
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0034_payment_charge_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hash",
            field=models.CharField(default=users.models.custom_hash_code, max_length=30),
        ),
        migrations.RunPython(set_users_hash),
    ]
