# Generated by Django 2.2.23 on 2021-05-27 08:27

import autoslug.fields
from django.db import migrations, models


def set_default_full_name(apps, *args, **kwargs):
    User_ = apps.get_model("users", "User")
    setattr(User_, "get_full_name", lambda self_: f"{self_.first_name} {self_.last_name}")
    for user in User_.objects.all():
        if not user.first_name:
            user.first_name = "trainer"
        if not user.last_name:
            user.last_name = "getrec"
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0035_user_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                null=True,
                populate_from="get_full_name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="trainer", max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="getrec", max_length=150),
        ),
        migrations.RunPython(
            set_default_full_name, reverse_code=migrations.RunPython.noop
        ),
    ]
