# Generated by Django 2.2.24 on 2021-10-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210711_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
