# Generated by Django 2.2.18 on 2021-02-05 12:58

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import trainer_classes.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trainer_classes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerclass",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="trainerclass",
            name="hash",
            field=models.CharField(
                default=trainer_classes.models.custom_hash_code, max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="trainerclass",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterUniqueTogether(
            name="trainerclass",
            unique_together={("name", "hash")},
        ),
        migrations.CreateModel(
            name="ClientClassSignUp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spots_count", models.PositiveIntegerField(default=1)),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email_address", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("promo_code", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "spots",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.jsonb.JSONField(
                            null=True
                        ),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("subscribe_to_emails", models.BooleanField(default=False)),
                ("agree_to_safety_waver", models.BooleanField(default=False)),
                (
                    "stripe_customer_id",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "geotag",
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
                ),
                (
                    "trainer_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clients",
                        to="trainer_classes.TrainerClass",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_sign_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Class Sign Up",
                "verbose_name_plural": "Client Class Sign Ups",
                "db_table": "client_class_sign_up",
                "unique_together": {("trainer_class", "email_address")},
            },
        ),
    ]
