# Generated by Django 2.2.18 on 2021-02-25 11:13

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0005_auto_20210218_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientclasssignup",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("not_paid", "Not Yet Paid"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="not_paid",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="PaymentLogs",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("event_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "event_data",
                    django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_logs",
                        to="trainer_classes.ClientClassSignUp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Class Payment Log",
                "verbose_name_plural": "Client Class PaymentLogs",
            },
        ),
    ]
