# Generated by Django 2.2.19 on 2021-03-16 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0009_auto_20210305_0801"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientclasssignup",
            name="client_sms_delivered",
        ),
        migrations.RemoveField(
            model_name="clientclasssignup",
            name="confirmation_email_delivered",
        ),
        migrations.RemoveField(
            model_name="clientclasssignup",
            name="confirmation_email_id",
        ),
        migrations.RemoveField(
            model_name="spot",
            name="delivered",
        ),
        migrations.RemoveField(
            model_name="spot",
            name="sg_message_id",
        ),
        migrations.RemoveField(
            model_name="trainerclass",
            name="trainer_sms_delivered",
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("sms", "Sms"),
                            ("email", "Email"),
                            ("push notifications", "Push notifications"),
                        ],
                        default="sms",
                        max_length=20,
                    ),
                ),
                ("before_hours", models.IntegerField(default=0)),
                (
                    "sg_message_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_subject",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "spot_email_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("delivered", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("all_client", models.BooleanField(default=False)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_notifications",
                        to="trainer_classes.ClientClassSignUp",
                    ),
                ),
                (
                    "trainer_class",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainer_notifications",
                        to="trainer_classes.TrainerClass",
                    ),
                ),
            ],
        ),
    ]
