# Generated by Django 2.2.20 on 2021-05-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0012_auto_20210412_1731"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientclasssignup",
            name="first_name_referred",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="clientclasssignup",
            name="last_name_referred",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
