# Generated by Django 2.2.20 on 2021-05-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0033_payment"),
        ("trainer_classes", "0016_auto_20210513_1220"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentlogs",
            name="client",
        ),
        migrations.AddField(
            model_name="paymentlogs",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="users.Payment",
            ),
        ),
    ]
