# Generated by Django 2.2.24 on 2021-06-07 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def export_spot_email_address(apps, *args, **kwargs):
    Notification = apps.get_model("trainer_classes", "Notification")
    for notification in Notification.objects.all():
        if notification.spot_email_address:
            notification.email_address = notification.spot_email_address
        elif notification.type == "sms" and notification.client:
            notification.phone_number = notification.client.phone_number
        elif notification.type == "email" and notification.client:
            notification.email_address = notification.client.email_address
        notification.save()


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0018_trainerclass_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="email_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RunPython(export_spot_email_address, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="notification",
            name="client",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="description",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="email_subject",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="spot_email_address",
        ),
        migrations.AddField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="before_hours",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="trainer_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trainer_classes.TrainerClass",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("sms", "Sms"), ("email", "Email"), ("push", "Push")],
                default="sms",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["sg_message_id"], name="trainer_cla_sg_mess_908b6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["created_at"], name="trainer_cla_created_d16832_idx"
            ),
        ),
    ]
