# Generated by Django 2.2.24 on 2021-06-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0019_auto_20210607_1449"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="before_hours",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
