# Generated by Django 2.2.24 on 2021-06-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0021_notification_email_subject"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clientclasssignup",
            unique_together={("trainer_class", "email_address")},
        ),
    ]
