# Generated by Django 2.2.24 on 2021-06-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0023_auto_20210615_1038'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='clientclasssignup',
        #     unique_together=set(),
        # ),
    ]
