# Generated by Django 2.2.23 on 2021-06-01 20:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainer_classes", "0024_auto_20210622_0938"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("promo", models.CharField(max_length=256)),
                (
                    "discount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RemoveIndex(
            model_name="trainerclass",
            name="trainer_cla_promo_c_ae35db_idx",
        ),
        migrations.RemoveField(
            model_name="trainerclass",
            name="promo_code",
        ),
        migrations.AddField(
            model_name="trainerclass",
            name="promo_code",
            field=models.ManyToManyField(blank=True, to="trainer_classes.PromoCode"),
        ),
    ]
