# Generated by Django 2.2.24 on 2021-07-05 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
        ("trainer_classes", "0027_auto_20210628_1205"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientclasssignup",
            name="reminder_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="django_celery_beat.PeriodicTask",
            ),
        ),
    ]
