# Generated by Django 2.2.24 on 2021-07-08 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0024_auto_20210618_1654'),
        ('trainer_classes', '0027_auto_20210628_1205'),
    ]

    operations = [
    ]
