# Generated by Django 2.2.24 on 2021-07-08 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0028_auto_20210705_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
