# Generated by Django 2.2.24 on 2021-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0030_auto_20210708_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientclasssignup',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Yet Paid'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('pending_capture', 'Pending Capture')], default='not_paid', max_length=10),
        ),
        # migrations.AlterUniqueTogether(
        #     name='clientclasssignup',
        #     unique_together=set(),
        # ),
    ]
