# Generated by Django 2.2.24 on 2021-07-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0031_auto_20210711_1813'),
        ('trainer_classes', '0028_merge_20210708_0211'),
    ]

    operations = [
    ]
