# Generated by Django 2.2.24 on 2021-08-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0033_auto_20210712_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='did_attend',
            field=models.BooleanField(null=True),
        ),
    ]
