# Generated by Django 2.2.24 on 2021-09-04 21:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import push_notifications.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0036_mockapnsdevice_mockwebpushdevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_class', models.CharField(max_length=1024)),
                ('device_id', models.UUIDField(verbose_name=push_notifications.models.Device)),
                ('when', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder='')),
            ],
        ),
    ]
