# Generated by Django 2.2.24 on 2021-09-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0038_auto_20210909_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientclasssignup',
            name='trainer_notified',
            field=models.BooleanField(default=False),
        ),
    ]
