# Generated by Django 2.2.24 on 2021-10-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_classes', '0041_auto_20210924_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerclass',
            name='trending_override',
            field=models.BooleanField(default=False),
        ),
    ]
