export const GET_CLASS_REQUEST = "Class/GET_CLASS_REQUEST";
export const GET_CLASS_ERROR = "Class/GET_CLASS_ERROR";
export const GET_CLASS_SUCCESS = "Class/GET_CLASS_SUCCESS";
export const SET_CLASS_FETCHING = "Class/SET_CLASS_FETCHING";
export const SET_CLASS_LINK = "Class/SET_CLASS_LINK";
export const SET_TRAINER_CLASSES = "Class/SET_TRAINER_CLASSES";
